### ISSUE TITLE
Allow disabling of logging

### ISSUE THREAD

**Issue by Coffee-Boyy** [MichaelVasseur/electron-ipc-bus#34]
Currently there is no external way to disable logging, you are only able to disable it via a switch internally.
I am recommending that either the bus utils logging export is available externally or there is a command line arg switch available to disable logging.

**Comment by emmkimme** [comment]
Hi,

Thank for your comment, did you have a look at exported methods
ActivateIpcBusTrace(enable: boolean)
ActivateServiceTrace(enable: boolean)

does it fit your needs ?
Else can you detail your expectations please.

Regards

**Comment by Coffee-Boyy** [comment]
My mind overlooked that assuming it did something else. Perfect, thanks!
